name: Release

on:
  push:

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    env:
      VERSION: 5.3.2 # This will be the tag ref later
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout build tools
        uses: actions/checkout@v2
        with:
          repository: EllisLab/ExpressionEngine-Build
          token: ${{ secrets.ORG_ACCESS_TOKEN }}
          path: build-tools
          ref: npm-update # Remove once testing is complete

      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          repository: ExpressionEngine/ExpressionEngine-User-Guide
          token: ${{ secrets.ORG_ACCESS_TOKEN }}
          path: ExpressionEngine-User-Guide

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v1

      - name: Install asdf dependencies
        working-directory: build-tools
        run: |
          asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
          bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
          asdf install

      - name: Install build tool dependencies
        working-directory: build-tools
        run: npm install

      - name: Run build process
        working-directory: build-tools
        env:
          RELEASE_KEY: ${{ secrets.RELEASE_KEY }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          APP_REPO_PATH: ${{ github.workspace }}
          DOCS_REPO_PATH: ${{ github.workspace }}/ExpressionEngine-User-Guide
        run: gulp default --local --head --skip-lint --version=${{ env.VERSION }}

      - name: Archive Build files
        uses: actions/upload-artifact@v2
        with:
          name: ExpressionEngine${{ env.VERSION }}
          path: build-tools/builds/ExpressionEngine${{ env.VERSION }}.zip

      - name: Archive Doc files
        uses: actions/upload-artifact@v2
        with:
          name: EEDocs${{ env.VERSION }}
          path: build-tools/builds/EEDocs${{ env.VERSION }}.zip

      - name: Archive Signature
        uses: actions/upload-artifact@v2
        with:
          name: Signature
          path: build-tools/builds/signature.txt

      - name: Directory Listing on Failure
        if: failure()
        run: |
          ls -latr
          ls -latr ExpressionEngine-User-Guide
          ls -latr build-tools
          ls -latr build-tools/builds
