name: Run Cypress Tests

on:
  push:
    branches:
      - release/6.0.0
      - testing/ee6
  pull_request:

jobs:
    cypress-tests:
        runs-on: ${{ matrix.os }}

        # services:
        #     mysql:
        #         image: mysql:5.7
        #         env:
        #             MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        #             MYSQL_ROOT_PASSWORD: 'root'
        #             MYSQL_DATABASE: 'ee-test'
        #         ports:
        #             - 3306/tcp
        #         options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        strategy:
            matrix:
                php: [7.1]
                os: [ubuntu-latest]

        name: P${{ matrix.php }} - ${{ matrix.os }}

        steps:

            - name: Checkout code
              uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v1
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, sqlite, libxml, mbstring, zip, pcntl, pdo, mysql, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Copy config.php
              run: php -r "file_exists('system/user/config/config.php') || copy('tests/cypress/support/config.ee6.php', 'system/user/config/config.php');"

            - name: Setup Permissions
              run: |
                cp tests/docker/EllisLabUpdate.pub system/ee/ExpressionEngine
                sudo chmod 666 system/user/config/config.php
                sudo chmod -R 777 system/user/cache
                sudo chmod -R 777 system/user/templates
                sudo chmod -R 777 system/user/language
                sudo chmod -R 777 tests/rspec/support/tmp
                sudo chmod -R 777 tests/rspec/support/file-sync/uploads
                sudo chmod -R 777 images
                sudo chmod -R 777 themes/user
                sudo chmod -R 777 tests/cypress/cypress/screenshots

            - name: Configure MySQL
              run: |
                sudo systemctl start mysql
                mysql -u root -proot -e 'CREATE DATABASE `ee-test`;'
                mysql -u root -proot -e 'SET GLOBAL sql_mode="ONLY_FULL_GROUP_BY,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION";'

            - name: Install PHP dependencies
              working-directory: tests/cypress
              run: composer install

            - name: Start PHP Server
              run: php -S localhost:8888 &

            - name: Run Cypress Tests
              uses: cypress-io/github-action@v1
              with:
                browser: chrome
                headless: true
                working-directory: tests/cypress

            - name: Archive screenshots
              uses: actions/upload-artifact@v1
              if: failure()
              with:
                name: cypress-tests
                path: tests/cypress/cypress/screenshots/

